services:
  backend:
    build: .
    container_name: model-registry-backend
    command: python model_registry/backend/app_backend.py
    ports:
      - "8051:8051"
    volumes:
      - ./model_registry:/app/model_registry
    networks:
      - ml_net
    restart: unless-stopped

  api:
    build: .
    container_name: model-registry-api
    command: >
      uvicorn model_registry.api.app_api:main
      --host 0.0.0.0
      --port 8081
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - R_API_URL=http://r-api:8501/predict
    volumes:
      - ./model_registry:/app/model_registry
    networks:
      - ml_net
    restart: unless-stopped

  r-api:
    build:
      context: .
      dockerfile: Dockerfile.r
    container_name: ml_r_api
    ports:
      - "8501:8501"
    volumes:
      - ./model_registry:/app/model_registry
    networks:
      - ml_net
    restart: unless-stopped

networks:
  ml_net:
    driver: bridge
