ml_model_configuration:
  model_identification:
    name: "Random Forest"
    version: "V.1.0"
    ID: "0001_[python]_penicillin_RF"    
    UUID: ""
    author: "Acosta-Pavas, J. C., Robles-Rodriguez, C. E., Griol, D., Daboussi, F., Aceves-Lara, C. A., & Corrales, D. C"  
    doi: "https://doi.org/10.1016/j.compchemeng.2024.108736"
    creation_date: "22-01-2024"
    project: "../project_info.yaml"
    status: "online"
    status_description: "Model is loaded and ready for predictions."      

  model_description:
    learner: "random_forest"
    model_type: "interpretable"    
    model_name: "Random Forest [Python implementation]"
    description: "Random forest (RF) builds multiple decision trees using different subsets of available features of the training data with bootstrapping and then combines their predictions to make a final prediction."
    language: 
      - name: "python"
      - version: "3.11.7"
    config_files: 
        model_file: "0001_[python]_penicillin_RF.pkl"
    packages:
        - package: "sklearn.ensemble"
          class: "RandomForestRegressor"
          version: "1.5.2"
    input_time_interval: 
        time_interval:
            value: 12
            unit: "minutes"
        aggregation:
            method: "NaN"
            description: "NaN"            
        description: "One measurement every 12 minutes"            

  training_information:            
    number_of_instances: 89800  
    hyperparameters:
      number_of_trees: 5     
      max_tree_depth: 7  
    validation: "10-fold CV - 3 repetitions"
    experiments_ID: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 19, 20, 21, 22, 24, 25, 26, 27, 29, 30, 31, 33, 34, 36, 37, 38, 39, 40, 42, 43, 44, 45, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 58, 59, 61, 62, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98, 99]

  inputs:
    features:
      - name: "temperature"
        type: "sensor"
        description: "Current temperature (T) in the bioreactor."
        units: "K"
        lag: 0     
        feature_scaling: 'none'
        expected_range:
          min: 298   # 25 °C
          max: 308   # 35 °C           
      - name: "pH"
        type: "sensor"
        description: "Current pH level in the bioreactor."
        units: "pH"
        lag: 0
        feature_scaling: 'none'  
        expected_range:
          min: 5.5
          max: 7.5        
      - name: "dissolved_oxygen_concentration"
        type: "sensor"
        description: "Dissolved oxygen (DO) concentration in the bioreactor."
        units: "mg/L"
        lag: 0
        feature_scaling: 'none'  
        expected_range:
          min: 0
          max: 10        
      - name: "agitator"
        type: "actuator"
        description: "Agitation speed in revolutions per minute."
        units: "rpm"
        lag: 0
        feature_scaling: 'none' 
        expected_range:
          min: 100
          max: 1200           
      - name: "CO2_percent_in_off_gas"
        type: "sensor"
        description: "CO2 percentage in the off-gas (CO2,og)."
        units: "%"
        lag: 0
        feature_scaling: 'none'
        expected_range:
          min: 0
          max: 10        
      - name: "oxygen_in_percent_in_off_gas"
        type: "sensor"
        description: "O2 percentage in the off-gas (O2,og)."
        units: "%"
        lag: 0
        feature_scaling: 'none'
        expected_range:
          min: 10
          max: 21        
      - name: "vessel_volume"
        type: "computed_variable"
        description: "Total volume of the bioreactor vessel (V)."
        units: "L"
        lag: 0
        feature_scaling: 'none'   
        expected_range:
          min: 1
          max: 1000                                                         
      - name: "sugar_feed_rate"
        type: "actuator"  
        description: "Sugar feed rate (Fs) into the bioreactor."
        units: "L/h"  
        lag: 0                                 
        feature_scaling: 'none'
        expected_range:
          min: 0
          max: 2                

  outputs:
    information:
      - name: "penicillin_concentration"
        description: "Prediction of the penicillin concentration."
        units: "g L−1"
        forecast_horizon: 0
        feature_scaling: 'none'
        expected_range:
          min: 0
          max: 50     