--
-- 01_schema.sql  —  CONSOLIDATED FermOps / STAMM database SCHEMA (DDL only)
--
-- Complete schema for the STAMM shared Postgres (postgres:16 + timescaledb),
-- consolidating the previous init chain (01_volcado + 02_fermops_compat +
-- 03_real lead-FK lift + Carlos's rich model columns + FL updated_at trigger).
-- All DATA lives in 02_seed.sql. Idempotent where the sources were.
--
-- Project lead = projects.lead_user_id uuid REFERENCES users(id) (Camilo's
-- 2026-05-22 spec). The legacy free-text `lead` column is dropped.
--
--
-- 01_volcado.sql (sanitized for postgres:16 + timescaledb)
--
-- Generated by infra/scripts/sanitize_volcado.py from Carlos's raw pg_dump.
-- DO NOT EDIT BY HAND — re-run the sanitizer instead. Manual edits will be
-- overwritten the next time the volcado is refreshed.
--
-- Sanitizer responsibilities:
--   * Strip pg18 \restrict / \unrestrict client directives.
--   * Strip pg17+ GUCs not supported by pg16 (currently: transaction_timeout).
--   * Rewrite 'OWNER TO postgres' -> 'OWNER TO CURRENT_USER' so the dump
--     loads against our 'stamm' superuser (compose default).
--   * Prepend CREATE EXTENSION timescaledb + timescaledb_pre_restore() so
--     the dump body's _timescaledb_catalog COPY blocks land cleanly.
--   * Append timescaledb_post_restore() wrapped in DO/EXCEPTION so a
--     catalog-version mismatch doesn't abort the init script. Without this,
--     02_fermops_compat.sql would never run.
--
-- 1. schema: 
ALTER SCHEMA public OWNER TO CURRENT_USER;
COMMENT ON SCHEMA public IS '';

-- 2. extensions: timescaledb, uuid-ossp, pgcrypto
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

COMMENT ON EXTENSION timescaledb IS 'Enables scalable inserts and complex queries for time-series data (Community Edition)';

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

-- 3. session configuration
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;  [stripped: pg17+ only GUC]
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

-- 4  tables core
--
-- TOC entry 316 (class 1259 OID 34607)
-- Name: access_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.access_requests (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    project_id uuid NOT NULL,
    reason text,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    resolved_at timestamp without time zone,
    resolved_by_user_id uuid
);


ALTER TABLE public.access_requests OWNER TO CURRENT_USER;

--
-- TOC entry 281 (class 1259 OID 34302)
-- Name: actuator_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actuator_states (
    "time" timestamp with time zone NOT NULL,
    run_id uuid NOT NULL,
    actuator_id uuid NOT NULL,
    value double precision
);


ALTER TABLE public.actuator_states OWNER TO CURRENT_USER;

--
-- TOC entry 280 (class 1259 OID 34291)
-- Name: actuators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actuators (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    actuator_id text,
    name text NOT NULL,
    variable text,
    unit text,
    range_min double precision,
    range_max double precision,
    description text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.actuators OWNER TO CURRENT_USER;

--
-- TOC entry 312 (class 1259 OID 34561)
-- Name: alert_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alert_rules (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    experiment_id uuid NOT NULL,
    name text NOT NULL,
    source_type text NOT NULL,
    source_id text NOT NULL,
    source_label text NOT NULL,
    condition text NOT NULL,
    threshold double precision,
    threshold_min double precision,
    threshold_max double precision,
    unit text,
    sustained_for_min double precision,
    severity text DEFAULT 'warning'::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    notes text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.alert_rules OWNER TO CURRENT_USER;

--
-- TOC entry 300 (class 1259 OID 34463)
-- Name: alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alerts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    condition text,
    message text,
    experiment_id uuid NOT NULL
);


ALTER TABLE public.alerts OWNER TO CURRENT_USER;

--
-- TOC entry 303 (class 1259 OID 34488)
-- Name: annotations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.annotations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    tag text,
    comment text,
    run_id uuid NOT NULL
);


ALTER TABLE public.annotations OWNER TO CURRENT_USER;

--
-- TOC entry 317 (class 1259 OID 34618)
-- Name: audit_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    actor_user_id uuid,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    detail text
);


ALTER TABLE public.audit_events OWNER TO CURRENT_USER;

--
-- TOC entry 319 (class 1259 OID 34640)
-- Name: bioreactor_instruments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bioreactor_instruments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    bioreactor_id uuid NOT NULL,
    instrument_id uuid NOT NULL
);


ALTER TABLE public.bioreactor_instruments OWNER TO CURRENT_USER;

--
-- TOC entry 309 (class 1259 OID 34536)
-- Name: department_laboratory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department_laboratory (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    department_id uuid,
    laboratory_id uuid
);


ALTER TABLE public.department_laboratory OWNER TO CURRENT_USER;

--
-- TOC entry 306 (class 1259 OID 34513)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.departments OWNER TO CURRENT_USER;

--
-- TOC entry 313 (class 1259 OID 34573)
-- Name: drift_detectors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drift_detectors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    detector_id text NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    description text,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.drift_detectors OWNER TO CURRENT_USER;

--
-- TOC entry 291 (class 1259 OID 34381)
-- Name: dynamic_model; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dynamic_model (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text,
    version text,
    url_endpoint text,
    information json,
    model_registry_id uuid
);


ALTER TABLE public.dynamic_model OWNER TO CURRENT_USER;

--
-- TOC entry 279 (class 1259 OID 34285)
-- Name: equipment_components; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_components (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    actuator_id uuid NOT NULL,
    sensor_id uuid NOT NULL,
    equipment_id uuid NOT NULL
);


ALTER TABLE public.equipment_components OWNER TO CURRENT_USER;

--
-- TOC entry 284 (class 1259 OID 34326)
-- Name: equipments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text,
    brand text,
    model text,
    version text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.equipments OWNER TO CURRENT_USER;

--
-- TOC entry 283 (class 1259 OID 34313)
-- Name: experiments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experiments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    experiment_id text,
    project_id uuid NOT NULL,
    lab_id uuid,
    vessel_id uuid,
    name text NOT NULL,
    description text,
    lead text,
    status text DEFAULT 'running'::text,
    mode text,
    scale text,
    organism text,
    medium text,
    is_reference boolean DEFAULT false,
    final_titer double precision,
    tags text[],
    initial_conditions jsonb,
    set_points jsonb,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.experiments OWNER TO CURRENT_USER;

--
-- TOC entry 304 (class 1259 OID 34496)
-- Name: experiments_equipments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experiments_equipments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    experiment_id uuid NOT NULL,
    equipment_id uuid NOT NULL
);


ALTER TABLE public.experiments_equipments OWNER TO CURRENT_USER;

--
-- TOC entry 318 (class 1259 OID 34629)
-- Name: instruments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.instruments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    instrument_id text NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    mode text NOT NULL,
    measures text[],
    typical_latency text,
    location text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.instruments OWNER TO CURRENT_USER;

--
-- TOC entry 294 (class 1259 OID 34403)
-- Name: laboratories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratories (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    location text
);


ALTER TABLE public.laboratories OWNER TO CURRENT_USER;

--
-- TOC entry 293 (class 1259 OID 34395)
-- Name: laboratory_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratory_project (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    laboratory_id uuid NOT NULL,
    project_id uuid NOT NULL
);


ALTER TABLE public.laboratory_project OWNER TO CURRENT_USER;

--
-- TOC entry 308 (class 1259 OID 34530)
-- Name: laboratory_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratory_user (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    laboratory_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.laboratory_user OWNER TO CURRENT_USER;

--
-- TOC entry 305 (class 1259 OID 34504)
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    location text
);


ALTER TABLE public.organizations OWNER TO CURRENT_USER;

--
-- TOC entry 307 (class 1259 OID 34522)
-- Name: organizations_departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations_departments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    organization_id uuid,
    department_id uuid
);


ALTER TABLE public.organizations_departments OWNER TO CURRENT_USER;

--
-- TOC entry 298 (class 1259 OID 34441)
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text
);


ALTER TABLE public.permissions OWNER TO CURRENT_USER;

--
-- TOC entry 314 (class 1259 OID 34586)
-- Name: phase_notes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phase_notes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    run_id uuid NOT NULL,
    phase text NOT NULL,
    text text NOT NULL,
    author_user_id uuid,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.phase_notes OWNER TO CURRENT_USER;

--
-- TOC entry 315 (class 1259 OID 34596)
-- Name: phase_overrides; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phase_overrides (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    run_id uuid NOT NULL,
    phase text NOT NULL,
    start_h double precision,
    end_h double precision,
    set_by_user_id uuid,
    set_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.phase_overrides OWNER TO CURRENT_USER;

--
-- TOC entry 288 (class 1259 OID 34362)
-- Name: predictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.predictions (
    "time" timestamp with time zone NOT NULL,
    run_id uuid NOT NULL,
    soft_sensor_id uuid NOT NULL,
    value double precision
);


ALTER TABLE public.predictions OWNER TO CURRENT_USER;

--
-- TOC entry 290 (class 1259 OID 34375)
-- Name: project_dynamic_models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_dynamic_models (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    project_id uuid NOT NULL,
    dynamic_model_id uuid NOT NULL
);


ALTER TABLE public.project_dynamic_models OWNER TO CURRENT_USER;

--
-- TOC entry 286 (class 1259 OID 34346)
-- Name: project_soft_sensors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_soft_sensors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    project_id uuid NOT NULL,
    soft_sensor_id uuid NOT NULL
);


ALTER TABLE public.project_soft_sensors OWNER TO CURRENT_USER;

--
-- TOC entry 285 (class 1259 OID 34335)
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text,
    project_id text NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    stamm_modules_id uuid
);


ALTER TABLE public.projects OWNER TO CURRENT_USER;

--
-- TOC entry 311 (class 1259 OID 34550)
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked boolean DEFAULT false
);


ALTER TABLE public.refresh_tokens OWNER TO CURRENT_USER;

--
-- TOC entry 310 (class 1259 OID 34542)
-- Name: resources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resources (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text
);


ALTER TABLE public.resources OWNER TO CURRENT_USER;

--
-- TOC entry 297 (class 1259 OID 34433)
-- Name: role_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permission (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    resource_id uuid
);


ALTER TABLE public.role_permission OWNER TO CURRENT_USER;

--
-- TOC entry 296 (class 1259 OID 34423)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    description text
);


ALTER TABLE public.roles OWNER TO CURRENT_USER;

--
-- TOC entry 282 (class 1259 OID 34307)
-- Name: runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    experiment_id uuid NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone
);


ALTER TABLE public.runs OWNER TO CURRENT_USER;

--
-- TOC entry 301 (class 1259 OID 34471)
-- Name: sensor_readings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensor_readings (
    "time" timestamp with time zone NOT NULL,
    run_id uuid NOT NULL,
    sensor_id uuid NOT NULL,
    value double precision
);


ALTER TABLE public.sensor_readings OWNER TO CURRENT_USER;

--
-- TOC entry 302 (class 1259 OID 34476)
-- Name: sensors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sensors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sensor_id text,
    name text NOT NULL,
    variable text,
    unit text,
    range_min double precision,
    range_max double precision,
    accuracy text,
    mode text DEFAULT 'online'::text,
    description text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.sensors OWNER TO CURRENT_USER;

--
-- TOC entry 292 (class 1259 OID 34389)
-- Name: simulations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.simulations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    value double precision,
    "time" date,
    dynamic_model_id uuid NOT NULL
);


ALTER TABLE public.simulations OWNER TO CURRENT_USER;

--
-- TOC entry 289 (class 1259 OID 34367)
-- Name: soft_sensor_metrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.soft_sensor_metrics (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    metric_name text,
    metric_value double precision,
    description text,
    experiment_id uuid NOT NULL,
    soft_sensor_id uuid NOT NULL
);


ALTER TABLE public.soft_sensor_metrics OWNER TO CURRENT_USER;

--
-- TOC entry 287 (class 1259 OID 34352)
-- Name: soft_sensors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.soft_sensors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    path_metadata text NOT NULL,
    path_model text NOT NULL
);


ALTER TABLE public.soft_sensors OWNER TO CURRENT_USER;

--
-- TOC entry 320 (class 1259 OID 34980)
-- Name: streaming_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.streaming_jobs (
    run_id uuid NOT NULL,
    status text NOT NULL,
    speed double precision DEFAULT 1 NOT NULL,
    duration_h double precision,
    signals text[] NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    last_heartbeat timestamp with time zone DEFAULT now() NOT NULL,
    bioprocess_t_h double precision DEFAULT 0 NOT NULL,
    rows_written_total integer DEFAULT 0 NOT NULL,
    pid integer,
    last_error text
);


ALTER TABLE public.streaming_jobs OWNER TO CURRENT_USER;

--
-- TOC entry 295 (class 1259 OID 34413)
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    laboratory_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    resource_type text,
    real_resource_id uuid,
    permission_id uuid
);


ALTER TABLE public.user_role OWNER TO CURRENT_USER;

--
-- TOC entry 299 (class 1259 OID 34451)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    phone text,
    password_hash text,
    external_provider text,
    external_id text,
    created_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true
);

ALTER TABLE public.users OWNER TO CURRENT_USER;

-- 5. constraints primary keys, unique
--
-- TOC entry 5551 (class 2606 OID 34616)
-- Name: access_requests access_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_requests
    ADD CONSTRAINT access_requests_pkey PRIMARY KEY (id);


--
-- TOC entry 5443 (class 2606 OID 34306)
-- Name: actuator_states actuator_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actuator_states
    ADD CONSTRAINT actuator_states_pkey PRIMARY KEY ("time", run_id, actuator_id);


--
-- TOC entry 5439 (class 2606 OID 34301)
-- Name: actuators actuators_actuator_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actuators
    ADD CONSTRAINT actuators_actuator_id_key UNIQUE (actuator_id);


--
-- TOC entry 5441 (class 2606 OID 34299)
-- Name: actuators actuators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actuators
    ADD CONSTRAINT actuators_pkey PRIMARY KEY (id);


--
-- TOC entry 5537 (class 2606 OID 34571)
-- Name: alert_rules alert_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alert_rules
    ADD CONSTRAINT alert_rules_pkey PRIMARY KEY (id);


--
-- TOC entry 5503 (class 2606 OID 34470)
-- Name: alerts alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);


--
-- TOC entry 5513 (class 2606 OID 34495)
-- Name: annotations annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_pkey PRIMARY KEY (id);


--
-- TOC entry 5554 (class 2606 OID 34626)
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);


--
-- TOC entry 5562 (class 2606 OID 34645)
-- Name: bioreactor_instruments bioreactor_instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bioreactor_instruments
    ADD CONSTRAINT bioreactor_instruments_pkey PRIMARY KEY (id);


--
-- TOC entry 5564 (class 2606 OID 34647)
-- Name: bioreactor_instruments bioreactor_instruments_uq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bioreactor_instruments
    ADD CONSTRAINT bioreactor_instruments_uq UNIQUE (bioreactor_id, instrument_id);


--
-- TOC entry 5529 (class 2606 OID 34541)
-- Name: department_laboratory department_laboratory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_laboratory
    ADD CONSTRAINT department_laboratory_pkey PRIMARY KEY (id);


--
-- TOC entry 5521 (class 2606 OID 34521)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 5540 (class 2606 OID 34585)
-- Name: drift_detectors drift_detectors_detector_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drift_detectors
    ADD CONSTRAINT drift_detectors_detector_id_key UNIQUE (detector_id);


--
-- TOC entry 5542 (class 2606 OID 34583)
-- Name: drift_detectors drift_detectors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drift_detectors
    ADD CONSTRAINT drift_detectors_pkey PRIMARY KEY (id);


--
-- TOC entry 5473 (class 2606 OID 34388)
-- Name: dynamic_model dynamic_model_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dynamic_model
    ADD CONSTRAINT dynamic_model_pkey PRIMARY KEY (id);


--
-- TOC entry 5437 (class 2606 OID 34290)
-- Name: equipment_components equipment_components_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_components
    ADD CONSTRAINT equipment_components_pkey PRIMARY KEY (id);


--
-- TOC entry 5453 (class 2606 OID 34334)
-- Name: equipments equipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipments
    ADD CONSTRAINT equipments_pkey PRIMARY KEY (id);


--
-- TOC entry 5515 (class 2606 OID 34501)
-- Name: experiments_equipments experiments_equipments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments_equipments
    ADD CONSTRAINT experiments_equipments_pkey PRIMARY KEY (id);


--
-- TOC entry 5449 (class 2606 OID 34325)
-- Name: experiments experiments_experiment_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_experiment_id_key UNIQUE (experiment_id);


--
-- TOC entry 5451 (class 2606 OID 34323)
-- Name: experiments experiments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_pkey PRIMARY KEY (id);


--
-- TOC entry 5558 (class 2606 OID 34639)
-- Name: instruments instruments_instrument_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_instrument_id_key UNIQUE (instrument_id);


--
-- TOC entry 5560 (class 2606 OID 34637)
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);


--
-- TOC entry 5481 (class 2606 OID 34412)
-- Name: laboratories laboratories_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_name_key UNIQUE (name);


--
-- TOC entry 5483 (class 2606 OID 34410)
-- Name: laboratories laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_pkey PRIMARY KEY (id);


--
-- TOC entry 5477 (class 2606 OID 34400)
-- Name: laboratory_project laboratory_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_project
    ADD CONSTRAINT laboratory_project_pkey PRIMARY KEY (id);


--
-- TOC entry 5527 (class 2606 OID 34535)
-- Name: laboratory_user laboratory_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_user
    ADD CONSTRAINT laboratory_user_pkey PRIMARY KEY (id, user_id, laboratory_id);


--
-- TOC entry 5461 (class 2606 OID 34361)
-- Name: soft_sensors ml_models_name_version_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.soft_sensors
    ADD CONSTRAINT ml_models_name_version_key UNIQUE (path_metadata, path_model);


--
-- TOC entry 5463 (class 2606 OID 34359)
-- Name: soft_sensors ml_soft_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.soft_sensors
    ADD CONSTRAINT ml_soft_pkey PRIMARY KEY (id);


--
-- TOC entry 5523 (class 2606 OID 34529)
-- Name: organizations_departments organizations_departments_organization_id_department_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations_departments
    ADD CONSTRAINT organizations_departments_organization_id_department_id_key UNIQUE (organization_id, department_id);


--
-- TOC entry 5525 (class 2606 OID 34527)
-- Name: organizations_departments organizations_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations_departments
    ADD CONSTRAINT organizations_departments_pkey PRIMARY KEY (id);


--
-- TOC entry 5519 (class 2606 OID 34512)
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- TOC entry 5495 (class 2606 OID 34450)
-- Name: permissions permissions_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);


--
-- TOC entry 5497 (class 2606 OID 34448)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5545 (class 2606 OID 34594)
-- Name: phase_notes phase_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_notes
    ADD CONSTRAINT phase_notes_pkey PRIMARY KEY (id);


--
-- TOC entry 5547 (class 2606 OID 34604)
-- Name: phase_overrides phase_overrides_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_overrides
    ADD CONSTRAINT phase_overrides_pkey PRIMARY KEY (id);


--
-- TOC entry 5549 (class 2606 OID 34606)
-- Name: phase_overrides phase_overrides_run_phase_uq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_overrides
    ADD CONSTRAINT phase_overrides_run_phase_uq UNIQUE (run_id, phase);


--
-- TOC entry 5466 (class 2606 OID 34366)
-- Name: predictions predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_pkey PRIMARY KEY ("time", run_id, soft_sensor_id);


--
-- TOC entry 5471 (class 2606 OID 34380)
-- Name: project_dynamic_models project_dynamic_models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_dynamic_models
    ADD CONSTRAINT project_dynamic_models_pkey PRIMARY KEY (id);


--
-- TOC entry 5459 (class 2606 OID 34351)
-- Name: project_soft_sensors project_soft_sensors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_soft_sensors
    ADD CONSTRAINT project_soft_sensors_pkey PRIMARY KEY (id);


--
-- TOC entry 5455 (class 2606 OID 34343)
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- TOC entry 5457 (class 2606 OID 34345)
-- Name: projects projects_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_project_id_key UNIQUE (project_id);


--
-- TOC entry 5533 (class 2606 OID 34558)
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 5535 (class 2606 OID 34560)
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- TOC entry 5531 (class 2606 OID 34549)
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);


--
-- TOC entry 5491 (class 2606 OID 34438)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5487 (class 2606 OID 34432)
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- TOC entry 5489 (class 2606 OID 34430)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 5447 (class 2606 OID 34312)
-- Name: runs runs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (id);


--
-- TOC entry 5506 (class 2606 OID 34475)
-- Name: sensor_readings sensor_readings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_readings
    ADD CONSTRAINT sensor_readings_pkey PRIMARY KEY ("time", run_id, sensor_id);


--
-- TOC entry 5509 (class 2606 OID 34485)
-- Name: sensors sensors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_pkey PRIMARY KEY (id);


--
-- TOC entry 5511 (class 2606 OID 34487)
-- Name: sensors sensors_sensor_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_sensor_id_key UNIQUE (sensor_id);


--
-- TOC entry 5475 (class 2606 OID 34394)
-- Name: simulations simulations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.simulations
    ADD CONSTRAINT simulations_pkey PRIMARY KEY (id);


--
-- TOC entry 5469 (class 2606 OID 34374)
-- Name: soft_sensor_metrics soft_sensor_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.soft_sensor_metrics
    ADD CONSTRAINT soft_sensor_metrics_pkey PRIMARY KEY (id);


--
-- TOC entry 5568 (class 2606 OID 34991)
-- Name: streaming_jobs streaming_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.streaming_jobs
    ADD CONSTRAINT streaming_jobs_pkey PRIMARY KEY (run_id);


--
-- TOC entry 5517 (class 2606 OID 34503)
-- Name: experiments_equipments uq_experiments_equipments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments_equipments
    ADD CONSTRAINT uq_experiments_equipments UNIQUE (experiment_id, equipment_id);


--
-- TOC entry 5479 (class 2606 OID 34402)
-- Name: laboratory_project uq_laboratory_project; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_project
    ADD CONSTRAINT uq_laboratory_project UNIQUE (laboratory_id, project_id);


--
-- TOC entry 5493 (class 2606 OID 34440)
-- Name: role_permission uq_role_permission; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id);


--
-- TOC entry 5485 (class 2606 OID 34422)
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);


--
-- TOC entry 5499 (class 2606 OID 34462)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 5501 (class 2606 OID 34460)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 5444 (class 1259 OID 34894)
-- Name: actuator_states_time_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX actuator_states_time_idx ON public.actuator_states USING btree ("time" DESC);


--
-- TOC entry 5552 (class 1259 OID 34617)
-- Name: idx_access_requests_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_access_requests_status ON public.access_requests USING btree (status);


--
-- TOC entry 5445 (class 1259 OID 34897)
-- Name: idx_actuator_states_run_time_actuator; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_actuator_states_run_time_actuator ON public.actuator_states USING btree (run_id, "time" DESC, actuator_id);


--
-- TOC entry 5538 (class 1259 OID 34572)
-- Name: idx_alert_rules_experiment; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alert_rules_experiment ON public.alert_rules USING btree (experiment_id);


--
-- TOC entry 5555 (class 1259 OID 34627)
-- Name: idx_audit_events_entity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit_events_entity ON public.audit_events USING btree (entity_type, entity_id);


--
-- TOC entry 5556 (class 1259 OID 34628)
-- Name: idx_audit_events_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_audit_events_timestamp ON public.audit_events USING btree ("timestamp" DESC);


--
-- TOC entry 5543 (class 1259 OID 34595)
-- Name: idx_phase_notes_run_phase; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_phase_notes_run_phase ON public.phase_notes USING btree (run_id, phase);


--
-- TOC entry 5464 (class 1259 OID 34898)
-- Name: idx_predictions_run_time_model; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_predictions_run_time_model ON public.predictions USING btree (run_id, "time" DESC, soft_sensor_id);


--
-- TOC entry 5504 (class 1259 OID 34896)
-- Name: idx_sensor_readings_run_time_sensor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_readings_run_time_sensor ON public.sensor_readings USING btree (run_id, "time" DESC, sensor_id);


--
-- TOC entry 5565 (class 1259 OID 34993)
-- Name: idx_streaming_jobs_heartbeat; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_streaming_jobs_heartbeat ON public.streaming_jobs USING btree (last_heartbeat DESC);


--
-- TOC entry 5566 (class 1259 OID 34992)
-- Name: idx_streaming_jobs_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_streaming_jobs_status ON public.streaming_jobs USING btree (status);


--
-- TOC entry 5467 (class 1259 OID 34895)
-- Name: predictions_time_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX predictions_time_idx ON public.predictions USING btree ("time" DESC);


--
-- TOC entry 5507 (class 1259 OID 34893)
-- Name: sensor_readings_time_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sensor_readings_time_idx ON public.sensor_readings USING btree ("time" DESC);

-- 6. constraints foreign keys
--
-- TOC entry 5604 (class 2606 OID 34883)
-- Name: department_laboratory FK_department_laboratory_department_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_laboratory
    ADD CONSTRAINT "FK_department_laboratory_department_id" FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- TOC entry 5605 (class 2606 OID 34888)
-- Name: department_laboratory FK_department_laboratory_laboratory_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_laboratory
    ADD CONSTRAINT "FK_department_laboratory_laboratory_id" FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- TOC entry 5602 (class 2606 OID 34873)
-- Name: laboratory_user FK_laboratories_users_id_laboratory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_user
    ADD CONSTRAINT "FK_laboratories_users_id_laboratory" FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- TOC entry 5603 (class 2606 OID 34878)
-- Name: laboratory_user FK_laboratories_users_id_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_user
    ADD CONSTRAINT "FK_laboratories_users_id_user" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5600 (class 2606 OID 34868)
-- Name: organizations_departments FK_organizations_departments_id_departments; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations_departments
    ADD CONSTRAINT "FK_organizations_departments_id_departments" FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- TOC entry 5601 (class 2606 OID 34863)
-- Name: organizations_departments FK_organizations_departments_id_organizations; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations_departments
    ADD CONSTRAINT "FK_organizations_departments_id_organizations" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- TOC entry 5612 (class 2606 OID 34683)
-- Name: access_requests access_requests_project_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_requests
    ADD CONSTRAINT access_requests_project_fk FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- TOC entry 5613 (class 2606 OID 34688)
-- Name: access_requests access_requests_resolver_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_requests
    ADD CONSTRAINT access_requests_resolver_fk FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5614 (class 2606 OID 34678)
-- Name: access_requests access_requests_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_requests
    ADD CONSTRAINT access_requests_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5607 (class 2606 OID 34653)
-- Name: alert_rules alert_rules_experiment_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alert_rules
    ADD CONSTRAINT alert_rules_experiment_fk FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 5615 (class 2606 OID 34693)
-- Name: audit_events audit_events_actor_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_actor_fk FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5616 (class 2606 OID 34698)
-- Name: bioreactor_instruments bioreactor_instruments_bio_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bioreactor_instruments
    ADD CONSTRAINT bioreactor_instruments_bio_fk FOREIGN KEY (bioreactor_id) REFERENCES public.equipments(id) ON DELETE CASCADE;


--
-- TOC entry 5617 (class 2606 OID 34703)
-- Name: bioreactor_instruments bioreactor_instruments_instr_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bioreactor_instruments
    ADD CONSTRAINT bioreactor_instruments_instr_fk FOREIGN KEY (instrument_id) REFERENCES public.instruments(id) ON DELETE CASCADE;


--
-- TOC entry 5572 (class 2606 OID 34728)
-- Name: actuator_states fk_actuator_states_actuator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actuator_states
    ADD CONSTRAINT fk_actuator_states_actuator FOREIGN KEY (actuator_id) REFERENCES public.actuators(id) ON DELETE CASCADE;


--
-- TOC entry 5573 (class 2606 OID 34733)
-- Name: actuator_states fk_actuator_states_run; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actuator_states
    ADD CONSTRAINT fk_actuator_states_run FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5593 (class 2606 OID 34828)
-- Name: alerts fk_alerts_experiment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT fk_alerts_experiment FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 5596 (class 2606 OID 34843)
-- Name: annotations fk_annotations_run; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT fk_annotations_run FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5597 (class 2606 OID 34848)
-- Name: annotations fk_annotations_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT fk_annotations_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5569 (class 2606 OID 34713)
-- Name: equipment_components fk_equipment_components_actuator; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_components
    ADD CONSTRAINT fk_equipment_components_actuator FOREIGN KEY (actuator_id) REFERENCES public.actuators(id) ON DELETE CASCADE;


--
-- TOC entry 5570 (class 2606 OID 34723)
-- Name: equipment_components fk_equipment_components_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_components
    ADD CONSTRAINT fk_equipment_components_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipments(id) ON DELETE CASCADE;


--
-- TOC entry 5571 (class 2606 OID 34718)
-- Name: equipment_components fk_equipment_components_sensor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_components
    ADD CONSTRAINT fk_equipment_components_sensor FOREIGN KEY (sensor_id) REFERENCES public.sensors(id) ON DELETE CASCADE;


--
-- TOC entry 5598 (class 2606 OID 34858)
-- Name: experiments_equipments fk_exp_eq_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments_equipments
    ADD CONSTRAINT fk_exp_eq_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipments(id) ON DELETE CASCADE;


--
-- TOC entry 5599 (class 2606 OID 34853)
-- Name: experiments_equipments fk_exp_eq_experiment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments_equipments
    ADD CONSTRAINT fk_exp_eq_experiment FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 5575 (class 2606 OID 34743)
-- Name: experiments fk_experiments_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT fk_experiments_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- TOC entry 5585 (class 2606 OID 34793)
-- Name: laboratory_project fk_lp_laboratory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_project
    ADD CONSTRAINT fk_lp_laboratory FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- TOC entry 5586 (class 2606 OID 34798)
-- Name: laboratory_project fk_lp_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratory_project
    ADD CONSTRAINT fk_lp_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- TOC entry 5582 (class 2606 OID 34783)
-- Name: project_dynamic_models fk_pdm_dynamic_model; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_dynamic_models
    ADD CONSTRAINT fk_pdm_dynamic_model FOREIGN KEY (dynamic_model_id) REFERENCES public.dynamic_model(id) ON DELETE CASCADE;


--
-- TOC entry 5583 (class 2606 OID 34778)
-- Name: project_dynamic_models fk_pdm_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_dynamic_models
    ADD CONSTRAINT fk_pdm_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- TOC entry 5578 (class 2606 OID 34758)
-- Name: predictions fk_predictions_run; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT fk_predictions_run FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5579 (class 2606 OID 34763)
-- Name: predictions fk_predictions_soft_sensor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT fk_predictions_soft_sensor FOREIGN KEY (soft_sensor_id) REFERENCES public.soft_sensors(id) ON DELETE CASCADE;


--
-- TOC entry 5576 (class 2606 OID 34748)
-- Name: project_soft_sensors fk_pss_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_soft_sensors
    ADD CONSTRAINT fk_pss_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- TOC entry 5577 (class 2606 OID 34753)
-- Name: project_soft_sensors fk_pss_soft_sensor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_soft_sensors
    ADD CONSTRAINT fk_pss_soft_sensor FOREIGN KEY (soft_sensor_id) REFERENCES public.soft_sensors(id) ON DELETE CASCADE;


--
-- TOC entry 5590 (class 2606 OID 34823)
-- Name: role_permission fk_role_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;


--
-- TOC entry 5591 (class 2606 OID 34708)
-- Name: role_permission fk_role_permission_resource; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_resource FOREIGN KEY (resource_id) REFERENCES public.resources(id) ON DELETE CASCADE;


--
-- TOC entry 5592 (class 2606 OID 34818)
-- Name: role_permission fk_role_permission_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- TOC entry 5574 (class 2606 OID 34738)
-- Name: runs fk_run_experiment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT fk_run_experiment FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 5594 (class 2606 OID 34833)
-- Name: sensor_readings fk_sensor_readings_run; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_readings
    ADD CONSTRAINT fk_sensor_readings_run FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5595 (class 2606 OID 34838)
-- Name: sensor_readings fk_sensor_readings_sensor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sensor_readings
    ADD CONSTRAINT fk_sensor_readings_sensor FOREIGN KEY (sensor_id) REFERENCES public.sensors(id) ON DELETE CASCADE;


--
-- TOC entry 5584 (class 2606 OID 34788)
-- Name: simulations fk_simulations_dynamic_model; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.simulations
    ADD CONSTRAINT fk_simulations_dynamic_model FOREIGN KEY (dynamic_model_id) REFERENCES public.dynamic_model(id) ON DELETE CASCADE;


--
-- TOC entry 5580 (class 2606 OID 34768)
-- Name: soft_sensor_metrics fk_ssm_experiment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.soft_sensor_metrics
    ADD CONSTRAINT fk_ssm_experiment FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 5581 (class 2606 OID 34773)
-- Name: soft_sensor_metrics fk_ssm_soft_sensor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.soft_sensor_metrics
    ADD CONSTRAINT fk_ssm_soft_sensor FOREIGN KEY (soft_sensor_id) REFERENCES public.soft_sensors(id) ON DELETE CASCADE;


--
-- TOC entry 5587 (class 2606 OID 34813)
-- Name: user_role fk_user_role_laboratory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_laboratory FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- TOC entry 5588 (class 2606 OID 34808)
-- Name: user_role fk_user_role_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- TOC entry 5589 (class 2606 OID 34803)
-- Name: user_role fk_user_role_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5608 (class 2606 OID 34663)
-- Name: phase_notes phase_notes_author_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_notes
    ADD CONSTRAINT phase_notes_author_fk FOREIGN KEY (author_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5609 (class 2606 OID 34658)
-- Name: phase_notes phase_notes_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_notes
    ADD CONSTRAINT phase_notes_run_fk FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5610 (class 2606 OID 34668)
-- Name: phase_overrides phase_overrides_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_overrides
    ADD CONSTRAINT phase_overrides_run_fk FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- TOC entry 5611 (class 2606 OID 34673)
-- Name: phase_overrides phase_overrides_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase_overrides
    ADD CONSTRAINT phase_overrides_user_fk FOREIGN KEY (set_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5606 (class 2606 OID 34648)
-- Name: refresh_tokens refresh_tokens_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- 7. Create hypertables for TimescaleDB (if not already created)

SELECT public.create_hypertable(
    'public.sensor_readings'::regclass,
    'time'::name,
    if_not_exists => TRUE
);

SELECT public.create_hypertable(
    'public.actuator_states'::regclass,
    'time'::name,
    if_not_exists => TRUE
);

SELECT public.create_hypertable(
    'public.predictions'::regclass,
    'time'::name,
    if_not_exists => TRUE
);


-- 8. FermOps additions: projects widening, model registry, FL

-- ============================================================
-- FermOps additions: projects widening, model registry, FL
-- ============================================================
BEGIN;

-- 9. Model registry + federated learning (proposal 2026-05-22) ----------
-- Replaces YAML-on-disk + path-only soft_sensors with proper relational
-- storage for ML models, plus federated-learning lineage tables.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + ALTER ... ADD COLUMN IF NOT
-- EXISTS, so re-running this script after a partial migration is safe.

-- 8.1 Projects: promote YAML fields to columns ---------------------------
-- 2026-05-22 (later same day): lead changed from free text to FK on
-- users.id (one PI per project). `lead text` if present from an older
-- init is left untouched here; the lift script in
-- 03_real_projects_and_models.sql drops it. The compat patch only adds
-- the new column.
ALTER TABLE public.projects
    ADD COLUMN IF NOT EXISTS objective     text,
    ADD COLUMN IF NOT EXISTS lead_user_id  uuid REFERENCES public.users(id),
    ADD COLUMN IF NOT EXISTS status        text NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS tags          text[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS started_at    timestamptz,
    ADD COLUMN IF NOT EXISTS closed_at     timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at    timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
    ALTER TABLE public.projects
        ADD CONSTRAINT projects_status_check
        CHECK (status IN ('planning', 'active', 'completed', 'archived'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 8.2 Federations (top-level FL collaboration) ---------------------------
CREATE TABLE IF NOT EXISTS public.federations (
    id                    uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    slug                  text NOT NULL UNIQUE,
    name                  text NOT NULL,
    description           text,
    coordinator_org_id    uuid REFERENCES public.organizations(id),
    aggregation_strategy  text NOT NULL,
    privacy_mechanism     text NOT NULL DEFAULT 'none',
    privacy_params        jsonb NOT NULL DEFAULT '{}'::jsonb,
    rounds_planned        integer NOT NULL DEFAULT 1,
    rounds_completed      integer NOT NULL DEFAULT 0,
    status                text NOT NULL DEFAULT 'planning',
    current_global_model_id uuid,  -- FK added below after models exists
    notes                 text,
    tags                  text[] NOT NULL DEFAULT '{}',
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    created_by_user_id    uuid REFERENCES public.users(id),
    CONSTRAINT federations_strategy_check CHECK (aggregation_strategy IN (
        'fedavg', 'fedprox', 'fedopt', 'fedmedian', 'scaffold', 'custom'
    )),
    CONSTRAINT federations_privacy_check CHECK (privacy_mechanism IN (
        'none', 'differential_privacy', 'secure_aggregation', 'homomorphic'
    )),
    CONSTRAINT federations_status_check CHECK (status IN (
        'planning', 'running', 'paused', 'completed', 'aborted'
    ))
);

-- 8.3 Models (replaces path-only soft_sensors) ---------------------------
CREATE TABLE IF NOT EXISTS public.models (
    id                       uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    slug                     text NOT NULL UNIQUE,
    name                     text NOT NULL,
    description              text,
    algorithm                text NOT NULL,
    status                   text NOT NULL DEFAULT 'draft',
    version                  text NOT NULL DEFAULT '1.0.0',

    -- Algo-specific config + IO contract + metrics (all JSONB).
    config                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    inputs                   jsonb NOT NULL DEFAULT '[]'::jsonb,
    outputs                  jsonb NOT NULL DEFAULT '[]'::jsonb,
    prediction_horizon_min   numeric,
    metrics                  jsonb NOT NULL DEFAULT '{}'::jsonb,

    -- Artifact (binary on disk, hash + path in DB).
    artifact_path            text,
    artifact_format          text,
    artifact_size_bytes      bigint,
    artifact_sha256          text,

    -- Training context.
    training_dataset_hash    text,
    training_started_at      timestamptz,
    training_completed_at    timestamptz,
    trained_by_user_id       uuid REFERENCES public.users(id),

    -- Single-parent lineage.
    parent_model_id          uuid REFERENCES public.models(id),
    superseded_by_model_id   uuid REFERENCES public.models(id),

    -- Federated-learning lineage.
    federation_id            uuid REFERENCES public.federations(id),
    federation_round         integer,
    federation_role          text,

    -- Validation gate.
    validation_status        text NOT NULL DEFAULT 'pending',
    validated_by_user_id     uuid REFERENCES public.users(id),
    validated_at             timestamptz,
    validation_notes         text,

    -- Deployment metadata.
    deployed_at              timestamptz,
    deployment_notes         text,

    -- Drift link.
    drift_detector_id        uuid REFERENCES public.drift_detectors(id),
    last_drift_check_at      timestamptz,
    drift_state              text,

    -- Documentation + lifecycle.
    notes                    text,
    tags                     text[] NOT NULL DEFAULT '{}',
    is_active                boolean NOT NULL DEFAULT true,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    created_by_user_id       uuid REFERENCES public.users(id),

    CONSTRAINT models_algorithm_check CHECK (algorithm IN (
        'decision_tree', 'random_forest', 'gradient_boosting', 'ensemble',
        'svm', 'linear_regression', 'logistic_regression',
        'neural_network', 'rnn', 'cnn', 'transformer',
        'gaussian_process', 'pls', 'pca', 'kmeans',
        'custom'
    )),
    CONSTRAINT models_status_check CHECK (status IN (
        'draft', 'training', 'trained', 'deployed', 'archived'
    )),
    CONSTRAINT models_validation_check CHECK (validation_status IN (
        'pending', 'approved', 'rejected'
    )),
    CONSTRAINT models_federation_role_check CHECK (
        federation_role IS NULL OR federation_role IN (
            'local_update', 'aggregated_global'
        )
    )
);

CREATE INDEX IF NOT EXISTS models_status_idx
    ON public.models (status) WHERE is_active;

CREATE INDEX IF NOT EXISTS models_algorithm_idx
    ON public.models (algorithm);

CREATE INDEX IF NOT EXISTS models_config_gin
    ON public.models USING gin (config);

CREATE INDEX IF NOT EXISTS models_metrics_gin
    ON public.models USING gin (metrics);

CREATE INDEX IF NOT EXISTS models_federation_round_idx
    ON public.models (federation_id, federation_round)
    WHERE federation_id IS NOT NULL;

-- Now that models exists, add the deferred FK from federations.
DO $$
BEGIN
    ALTER TABLE public.federations
        ADD CONSTRAINT federations_current_global_model_fk
        FOREIGN KEY (current_global_model_id) REFERENCES public.models(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 8.4 Project ↔ Model link table -----------------------------------------
CREATE TABLE IF NOT EXISTS public.project_models (
    id          uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    project_id  uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    model_id    uuid NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
    role        text NOT NULL DEFAULT 'primary',
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT project_models_pmr_uq UNIQUE (project_id, model_id, role)
);

-- 8.5 Federation ↔ Project link table -----------------------------------
CREATE TABLE IF NOT EXISTS public.federation_participants (
    id              uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    federation_id   uuid NOT NULL REFERENCES public.federations(id) ON DELETE CASCADE,
    project_id      uuid NOT NULL REFERENCES public.projects(id),
    role            text NOT NULL DEFAULT 'participant',
    joined_at       timestamptz NOT NULL DEFAULT now(),
    left_at         timestamptz,
    local_dataset_size      bigint,
    local_data_hash         text,
    last_contribution_round integer,
    CONSTRAINT federation_participants_role_check CHECK (
        role IN ('coordinator', 'participant')
    ),
    CONSTRAINT federation_participants_fp_uq UNIQUE (federation_id, project_id)
);

-- 8.6 Multi-parent lineage (federated aggregation edges) ----------------
CREATE TABLE IF NOT EXISTS public.model_contributions (
    id                      uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    aggregated_model_id     uuid NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
    contributor_model_id    uuid NOT NULL REFERENCES public.models(id),
    federation_id           uuid NOT NULL REFERENCES public.federations(id) ON DELETE CASCADE,
    round_number            integer NOT NULL,
    contribution_weight     numeric NOT NULL DEFAULT 1.0,
    contribution_metrics    jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT model_contributions_acr_uq
        UNIQUE (aggregated_model_id, contributor_model_id, round_number)
);

CREATE INDEX IF NOT EXISTS model_contributions_agg_idx
    ON public.model_contributions (aggregated_model_id);

CREATE INDEX IF NOT EXISTS model_contributions_contrib_idx
    ON public.model_contributions (contributor_model_id);

CREATE INDEX IF NOT EXISTS model_contributions_round_idx
    ON public.model_contributions (federation_id, round_number);

-- 8.7 Update projects with real metadata ----------------------------------
-- UUIDs from the volcado seed:
--   P0001 = ccccccc1-cccc-cccc-cccc-cccccccccccc
--   P0002 = ccccccc2-cccc-cccc-cccc-cccccccccccc
--   P0003 = ccccccc3-cccc-cccc-cccc-cccccccccccc

-- 2026-05-22 (afternoon): drop the obsolete `lead text` column if a prior
-- init created it. The new column is `lead_user_id uuid REFERENCES users(id)`
-- (added in compat patch section 8.1). Idempotent: IF EXISTS.
ALTER TABLE public.projects DROP COLUMN IF EXISTS lead;

-- Backfill for existing volumes where `models` was created before the
-- doi/authors split or before the high-fidelity YAML columns. Safe no-ops
-- on fresh boots (CREATE TABLE above already includes them).
ALTER TABLE public.models
    ADD COLUMN IF NOT EXISTS doi                  text,
    ADD COLUMN IF NOT EXISTS authors              text,
    ADD COLUMN IF NOT EXISTS learner              text,
    ADD COLUMN IF NOT EXISTS model_type           text,
    ADD COLUMN IF NOT EXISTS external_uuid        text,
    ADD COLUMN IF NOT EXISTS creation_date        text,
    ADD COLUMN IF NOT EXISTS status_description   text,
    ADD COLUMN IF NOT EXISTS language             jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS packages             jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS config_files         jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS input_time_interval  jsonb,
    ADD COLUMN IF NOT EXISTS model_architecture   jsonb,
    ADD COLUMN IF NOT EXISTS training_information jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Keep federations.updated_at fresh.
CREATE OR REPLACE FUNCTION public.tg_federations_set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS federations_set_updated_at ON public.federations;

CREATE TRIGGER federations_set_updated_at
    BEFORE UPDATE ON public.federations
    FOR EACH ROW
    EXECUTE FUNCTION public.tg_federations_set_updated_at();


-- Add experiment_models junction table to link experiments and models
CREATE TABLE IF NOT EXISTS public.experiment_models (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id UUID REFERENCES public.experiments(id) ON DELETE CASCADE,
    model_id UUID REFERENCES public.models(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'attached',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
-- Allow NULLs for existing data compatibility: experiment_id and model_id are nullable

COMMIT;

-- end of 01_schema.sql --

